### ISSUE TITLE
Borrow this thing to make the oxygenite tank distinguishable from the oxygen tank (maybe)

### ISSUE THREAD

**Issue by BlueTheKing** [ChikoEduardo/BTE#1]
[Pull request](https://github.com/Regalis11/Barotrauma/pull/798)
The "meditem" to "smallitem" thing can be used too.

**Comment by TheGoldenGuardian** [comment]
Not sure why the color would be changed, Oxygenite in the context of BTE is just the liquid put into a regular Oxygen Tank.

**Comment by ChikoEduardo** [comment]
Yeah, we don't want to make things way too easy for people. :3

**Comment by BlueTheKing** [comment]
Hmmm

**Comment by BlueTheKing** [comment]
Lmao, forgot this was still open.
